# SPDX-License-Identifier: Apache-2.0
# Copyright 2024-2026 Paul Fremantle

"""A turned profile read from a part someone actually made.

Every other piece of turned-step evidence in this repository is synthetic: one golden fixture
and a handful of stacked `Cylinder` calls. The two vendored corpora contribute nothing —
measured, all 50 NIST and MFCAD++ parts are milled prismatic and report **zero** turned steps.
So the family with the most tolerance-sensitive geometry had the least real geometry behind it,
and that is what let the defect below sit in a pinned fixture unnoticed.

Two parts from the author's own Gramel project, generated by build123d, both small enough that
the recogniser's absolute constants are comparable to their features — the ordinary case for a
turned part, not an edge case, and precisely where reading an OD by proximity rather than by
containment goes wrong.

``GRM-03`` is a 23.5 mm thumbwheel drive screw turned about **X**. ``GRM-05`` is a 32 mm depth
lock bolt turned about **Z**, and it is here for coverage rather than as a regression: its
profile at 1:1 is the same before and after the containment fix. What it adds is a second real
profile, on the other axis, with a 0.25 mm diameter change between two of its rungs — a step
finer than anything the synthetic fixtures contain.
"""

from __future__ import annotations

from pathlib import Path

import pytest

pytest.importorskip("build123d")

from build123d import import_step  # noqa: E402

from b123d_recognisers import recognise_turned_steps  # noqa: E402

CORPUS = Path(__file__).parent / "corpus" / "gramel"

#: Each part's rungs, as ``(diameter, lo, hi)``. Every rung must report the band that covers it.
#:
#: GRM-03's first rung is the one that used to be wrong: Ø6 runs from 0 to 0.5, and the Ø10 band
#: starting at 0.8 reached back over it on a 0.7 mm proximity pad.
EXPECTED = {
    "GRM-03_thumbwheel_drive_screw": [
        (6.0, 0.0, 0.5),
        (10.0, 0.5, 2.5),
        (5.0, 2.5, 5.5),
        (3.0, 5.5, 23.5),
    ],
    "GRM-05_depth_lock_bolt": [(10.0, 0.0, 14.0), (6.25, 14.0, 19.0), (6.0, 19.0, 32.0)],
}


def _profile(part):
    return [
        (round(step.diameter, 3), round(step.lo, 3), round(step.hi, 3))
        for step in sorted(recognise_turned_steps(part), key=lambda step: step.lo)
    ]


@pytest.mark.parametrize("name", sorted(EXPECTED))
def test_every_rung_reports_the_band_that_covers_it(name):
    """Each rung, at the size the part is actually made.

    GRM-03 is the regression: before the containment fix its first rung reported Ø10, the
    widest band on the screw, which does not reach that rung at all. The Ø10 span starts at 0.8
    and the rung is 0 to 0.5, so a 0.7 mm proximity pad bridged the 0.3 mm gap and outvoted the
    Ø6 band the rung sits inside. That is not a small-scale artefact, which is how it was first
    described — the part is 23.5 mm and modelled 1:1.

    GRM-05 passes on either side of that fix and is pinned for coverage: a second real profile,
    turned about Z rather than X, whose middle rung differs from its neighbour by 0.25 mm.
    """

    assert _profile(import_step(str(CORPUS / f"{name}.step"))) == EXPECTED[name]


@pytest.mark.parametrize("name", sorted(EXPECTED))
@pytest.mark.parametrize("factor", (5.0, 100.0))
def test_the_same_part_modelled_larger_has_the_same_profile(factor, name):
    """Scale-free as ratios, so no assertion depends on a length.

    0.05× is deliberately absent, for a different reason on each part and neither of them this
    branch's doing. GRM-03 gains a spurious shoulder and splits one rung into two of equal
    diameter. GRM-05's Ø6.25 band reports as Ø0.31 rather than Ø0.3125, because
    ``analyse_cylinders`` rounds every diameter to two decimals — fine at millimetre scale, a
    0.8% error at a twentieth of it. Pinning either would only record today's wrong answer.
    """

    rungs = EXPECTED[name]
    part = import_step(str(CORPUS / f"{name}.step"))
    widest = max(diameter for diameter, _, _ in rungs)
    span = max(hi for _, _, hi in rungs) - min(lo for _, lo, _ in rungs)
    expected = [
        (round(diameter / widest, 6), round((hi - lo) / span, 6)) for diameter, lo, hi in rungs
    ]

    scaled = _profile(part.scale(factor))
    widest_scaled = max(diameter for diameter, _, _ in scaled)
    span_scaled = max(hi for _, _, hi in scaled) - min(lo for _, lo, _ in scaled)
    actual = [
        (round(diameter / widest_scaled, 6), round((hi - lo) / span_scaled, 6))
        for diameter, lo, hi in scaled
    ]

    assert actual == expected
