# SPDX-License-Identifier: Apache-2.0
# Copyright 2024-2026 Paul Fremantle

"""A turned profile read from a part someone actually made.

Every other piece of turned-step evidence in this repository is synthetic: one golden fixture
and a handful of stacked `Cylinder` calls. The two vendored corpora contribute nothing —
measured, all 50 NIST and MFCAD++ parts are milled prismatic and report **zero** turned steps.
So the family with the most tolerance-sensitive geometry had the least real geometry behind it,
and that is what let the defect below sit in a pinned fixture unnoticed.

``GRM-03`` is a thumbwheel drive screw from the author's own Gramel project, 23.5 mm long,
generated by build123d. It is here because it is small enough that the recogniser's absolute
constants are comparable to its features — which is the ordinary case for a turned part, not an
edge case, and is precisely where reading an OD by proximity rather than by containment goes
wrong.
"""

from __future__ import annotations

from pathlib import Path

import pytest

pytest.importorskip("build123d")

from build123d import import_step  # noqa: E402

from b123d_recognisers import recognise_turned_steps  # noqa: E402

FIXTURE = Path(__file__).parent / "corpus" / "gramel" / "GRM-03_thumbwheel_drive_screw.step"

#: The screw's external bands, read from ``analyse_cylinders``. Each rung of the profile must
#: report the band that covers it, and the first is the one that used to be wrong: Ø6 runs from
#: 0 to 0.5, and the Ø10 band starting at 0.8 reached back over it.
EXPECTED = [(6.0, 0.0, 0.5), (10.0, 0.5, 2.5), (5.0, 2.5, 5.5), (3.0, 5.5, 23.5)]


def _profile(part):
    return [
        (round(step.diameter, 3), round(step.lo, 3), round(step.hi, 3))
        for step in sorted(recognise_turned_steps(part), key=lambda step: step.lo)
    ]


def test_every_rung_reports_the_band_that_covers_it():
    """The regression, at the size the part is actually made.

    Before the fix this reported the first rung at Ø10 — the widest band on the screw, which
    does not reach the rung at all. Its span starts at 0.8 and the rung is 0 to 0.5; a 0.7 mm
    proximity pad bridged the 0.3 mm gap and outvoted the Ø6 band the rung sits inside.

    This is not a small-scale artefact, which is how it was first described. The part is 23.5 mm
    and modelled 1:1.
    """

    assert _profile(import_step(str(FIXTURE))) == EXPECTED


@pytest.mark.parametrize("factor", (5.0, 100.0))
def test_the_same_screw_modelled_larger_has_the_same_profile(factor):
    """Scale-free as ratios, so no assertion depends on a length.

    0.05× is deliberately absent: at ~1.2 mm overall the recogniser finds an extra shoulder and
    splits one rung into two of equal diameter. That is a separate defect, unchanged by the
    containment fix — it reproduces identically with and without it — and pinning it here would
    only record today's wrong answer.
    """

    part = import_step(str(FIXTURE))
    widest = max(diameter for diameter, _, _ in EXPECTED)
    span = max(hi for _, _, hi in EXPECTED) - min(lo for _, lo, _ in EXPECTED)
    expected = [
        (round(diameter / widest, 6), round((hi - lo) / span, 6))
        for diameter, lo, hi in EXPECTED
    ]

    scaled = _profile(part.scale(factor))
    widest_scaled = max(diameter for diameter, _, _ in scaled)
    span_scaled = max(hi for _, _, hi in scaled) - min(lo for _, lo, _ in scaled)
    actual = [
        (round(diameter / widest_scaled, 6), round((hi - lo) / span_scaled, 6))
        for diameter, lo, hi in scaled
    ]

    assert actual == expected
